import Masonry from "react-masonry-css";
import PostItem from "../../components/post-item/PostItem";
import './Discover.css';

function Discover() {
    return <Masonry breakpointCols={2}
        className="posts-grid flex-1 p-6"
        columnClassName="posts-grid-column">
        <PostItem post={{ content: "sapien nec sagittis. Tellus orci ac auctor augue mauris augue neque. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Mauris augue neque gravida in fermentum. Netus et malesuada fames ac turpis egestas maecenas pharetra. Quisque non tellus orci ac. Nunc lobortis mattis aliquam faucibus. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Enim nulla aliquet porttitor lacus luctus. Erat imperdiet sed euismod nisi. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Amet risus nullam eget felis eget nunc lobortis. Urna id volutpat lacus laoreet non curabitur gravida. Consequat interdum varius sit amet. Nunc lobortis mattis aliquam faucibus purus." }} />
        <PostItem post={{ content: "sapievarius sit amet. Nunc lobortis mattis aliquam faucibus purus." }} />
        <PostItem post={{ content: "sapien nec sagittis. Tellus orci ac auctor augue mauris augue neque. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Mauris augue neque gravida in fermentum. Netus et malesuada fames ac turpis egestas maecenas pharetra. Quisque non tellus orci ac. Nunc lobortis mattis aliquam faucibus. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Enim nulla aliquet porttitor lacus luctus. Erat imperdiet sed euismod nisi. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Amet risus nullam eget felis eget nunc lobortis. Urna id volutpat lacus laoreet non curabitur gravida. Consequat interdum varius sit amet. Nunc lobortis mattis aliquam faucibus purus." }} />
        <PostItem post={{ content: "sapien nec sagittis. Tellre quam viverra orci sagittis eu volutpat odio facilisis mauris. Mauris augue neque gravida in fermentum. Netus et malesuada fames ac turpis egestas maecenas pharetra. Quisque non tellus orci ac. Nunc lobortis mattis aliquam faucibus. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Enim nulla aliquet porttitor lacus luctus. Erat imperdiet sed euismod nisi. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Amet risus nullam eget felis eget nunc lobortis. Urna id volutpat lacus laoreet non curabitur gravida. Consequat interdum varius sit amet. Nunc lobortis mattis aliquam faucibus purus." }} />
        <PostItem post={{ content: "slisis mauris. Mauris augue neque gravida in fermentum. Netus et malesuada fames ac turpis egestas maecenas pharetra. Quisque non tellus orci ac. Nunc lobortis mattis aliquam faucibus. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Enim nulla aliquet porttitor lacus luctus. Erat imperdiet sed euismod nisi. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Amet risus nullam eget felis eget nunc lobortis. Urna id volutpat lacus laoreet non curabitur gravida. Consequat interdum varius sit amet. Nunc lobortis mattis aliquam faucibus purus." }} />
        <PostItem post={{ content: "sapien nec sagittis. Tellus orci ac auctor augue mauris augue neque. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Mauris augue neque gravida in fermentum. Netus et malesuada fames ac turpis egestas maecenas pharetra. Quisque non tellus orci ac. Nunc lobortis mattis aliquam faucibus. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Enim nulla aliquet porttitor lacus luctus. Erat imperdiet sed euismod nisi. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Amet risus nullam eget felis eget nunc lobortis. Urna id volutpat lacus laoreet non curabitur gravida. Consequat interdum varius sit amet. Nunc lobortis mattis aliquam faucibus purus." }} />
        <PostItem post={{ content: "sapien nec sagittis. Tellus orci ac auctor augue mauris augue neque. Ornare quam viverra orci sagittis eu volutpat odio facilisis mauris. Mauris augue neque gravida in fermentum. Netus et malesuada fames ac turpis egestas maecenas pharetra. Quisque non tellus orci ac. Nunc lobortis mattis aliquam faucibus. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Enim nulla aliquet porttitor lacus luctus. Erat imperdiet sed euismod nisi. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Amet risus nullam eget felis eget nunc lobortis. Urna id volutpat lacus laoreet non curabitur gravida. Consequat interdum varius sit amet. Nunc lobortis mattis aliquam faucibus purus." }} />
    </Masonry>
}

export default Discover;